---
title: "Problem Set 4"
format: pdf
---

In this problem set, you will continue to be asked to work with the gamma distribution and you may find it useful to refer back to the previous problem set and/or solutions. I recommend Wikipedia as a reference, `https://en.wikipedia.org/wiki/Gamma_distribution`. 

Keep your rendered `.pdf` to no more than 6 pages. Only provide code in the rendered `.pdf` when it is specifically requested.

1. Continue using four sets of values for the shape parameter $\alpha$ and rate parameter $\lambda$: $\left(\alpha_1, \lambda_1\right) = \left(0.5, 0.5\right)$, $\left(\alpha_2, \lambda_2\right) = \left(2, 1\right)$, $\left(\alpha_3, \lambda_3\right) = \left(0.5, 1\right)$, and $\left(\alpha_4, \lambda_4\right) = \left(2, 0.5\right)$, and store these values in a matrix `Y` with 4 rows and 2 columns, where the first column corresponds to the shape parameter, the second column corresponds to the rate parameter, and the rows correspond to the parameters in the order provided above.

(a) Create a matrix `W` that with 4 rows and $100,000$ columns. Fill each row of `W` with $100,000$ draws from the corresponding gamma distribution using the `rgamma` function. Print the code you use to create this matrix to the rendered `.pdf`.

(b) Create a matrix `V` that with 4 rows and $100,000$ columns. Fill each row of `V` with $100,000$ draws from the corresponding gamma distribution using the `rgamma` function obtained by simulating from gamma distributions with shape $0.5$ or $2$ and rate $1$ using `rgamma` and applying simple mathematical operations. Print the code you use to create this matrix to the rendered `.pdf`. You may need to remind yourself of some gamma distribution facts.

(c) Again, consider a sequence of values given by `x <- seq(0.01, 6, by = 0.01)`. Create two matrices `pW` and `pV` each with the same number of rows as `W` and the same number of columns as the length of `x` minus 1 with all elements equal to `NA`. Fill each element of `pW` and `pV` with the proportion of elements in the corresponding row of `W` or `V` between the corresponding element of `x` and the next largest element of `x`. Print the code you use to create these matrices matrix to the rendered `.pdf`.

(d) Create a vector `xmid` that has the same number of elements as the length of `x` minus one, and set the elements of `xmid` to be the midpoints between each element of `x`. Print the code you use to create this matrix to the rendered `.pdf`.

(e) Create a single plot that includes 8 lines corresponding to each row of `pW` and each row of `pV` plotted against `xmid`. Use different colors lines to reflect the parameters of the gamma distribution each row of `pV` or `pW` describes and use different line types for whether or not the line was computed from `pV` or `pW`. Make sure that your plot is clearly annotated and has an informative legend.

(f) Based on what you find in (e), explain in at most one sentence whether or not the approaches for simulating gamma random variables in (a) and (b) are equivalent.

(g) Create two matrices `qW` and `qV` each with the same number of rows as `W` and the same number of columns as the length of `x` with all elements equal to `NA`. Fill each element of `qW` and `qV` with the proportion of elements in the corresponding row of `W` or `V` that are less than or equal to the corresponding element of `x`. Create a third matrix `qT` with the same dimensions as `qW` and `qV`. Fill each element of `qT` with the probability that a gamma random variable with parameters corresponding to the same row of `Y` is less than or equal to the corresponding element of `x`. Use one of the functions that starts with a letter and ends with `gamma`. Print the code you use to create `qT` to the rendered `.pdf`.

(h) Create a single plot that includes 12 lines corresponding to each row of `qW`, each row of `qV`, and each row of `qT` plotted against `x`. Use different colors lines to reflect the parameters of the gamma distribution each row of `qV`, `qW`, or `qT` describes and use different line types for whether or not the line was computed from `qV`, `qW`, or `qT`. Make sure that your plot is clearly annotated and has an informative legend.

(i) In at most two sentences, explain the differences between lines corresponding to the same gamma distribution in (h), if there are any. 

2. This question is introducing the multivariate normal distribution, which I don't expect you to be familiar with yet, and the computational challenges that come up when we work with it.

(a) Simulate $3$ independent standard normal variables and store them in a vector called `z`. Print the code you use to create `z` to the rendered `.pdf`.

(b) Write a for loop that generates $3$ normal random variables stored in a vector `y` using `z` and basic mathematical operations, where the first element of `y` has a standard normal distribution and the remaining elements of `y` conditional on previous elements have a normal distribution with a mean that of $0.5$ times the last element of `y` and variance $0.75$. Print the code you use to create `z` to the rendered `.pdf`.

(c) Create a $3\times 3$ matrix $D$ that creates the same vector `y` from `z` if you apply `D%*%z`. You'll need to do some algebra. Print the code you use to create `D` to the rendered `.pdf`.

(d) Print one line of code you could use to check that your construction of `D` in (c) is correct based on what you obtained in (b).

(e) Using the `arcovariance.R` code, create a $3\times 3$ version of the matrix `C`. You could just take the first 3 rows and first 3 columns of `C`. Print the code you need to compute the Cholesky decomposition of this $3 \times 3$ matrix and take its transpose the rendered `.pdf`.

(f) Create a plot of the nonzero elements of $D$ against the nonzero elements of the transposed Cholesky decomposition in (e). Make sure that your plot is clearly annotated.

(g) Write a function that takes $n$, the length of the vector that you'd like to simulate and $\rho$, an autocovariance parameter and returns an $n$ dimensional random vector obtained by constructing a covariance matrix $\boldsymbol C$ with elements $c_{ij} = \rho^{\left|i-j\right|}$, taking its Cholesky decomposition, and multiplying the transpose of its Cholesky decomposition by $n$ independent standard normal random variables (note - order matters). Print the code you use define the function to the rendered `.pdf`.

(h) Write a for loop that generates $50$ random vectors of length $2$ using your function from $(a)$ with $\rho = 0.99$ and stores them in a $2\times 50$ matrix called `mat`. Print the code you use to create this matrix and implement this for loop to the rendered `.pdf`. Include a line of code that ensures that the values you obtain are reproducible by someone else on another computer.

(i) Evaluate the sample means, covariances, and correlation of the bivariate random variables you simulated in (b). Summarize your results in a table made using `kable`. Use your knowledge from previous statistics classes to compute these quantities.

(j) In at most one sentence, describe how the results in the table in (c) relate to what you would expect to see.

3. Consider a truncated gamma random variable $x$ with shape $a$ and rate $b$ that is constrained to the interval $\left(0, c\right)$. The density $g\left(x | a, b, c\right)$ of this random variable satisfies:

\begin{align*}
g\left(x | a, b, c\right) = \frac{f\left(x | a, b\right)}{F\left(c | a, b\right)},
\end{align*}
where $f\left(x | a, b\right)$ is the density of a gamma random variable with shape $a$ and rate $b$ and $F\left(c | a, b\right)$ is the probability that a gamma random variable with shape $a$ and rate $b$ is less than or equal to $c$.

(a) The CDF of this truncated gamma random variable is $G\left(x | a, b, c\right) = \frac{F\left(x | a, b\right)}{F\left(c | a, b\right)}$. Write a function that takes a probability $p$, Gamma shape and rate parameters $a$ and $b$, and an upper bound $c$ and returns the inverse CDF of this truncated random variable. Print the code you use define the function to the rendered `.pdf`.

(b) Use the function from part (a) and uniform random variables to simulate $1,000$ draws from a truncated gamma distribution with shape $1$ and rate $1$ constrained to the interval $\left(0, 1\right)$. Make a histogram of the draws using the `hist` function setting the arguments `freq = FALSE` and `br = seq(0, 1, length.out = 10)`.

(c) Write a for loop that generates $1,000$ draws from a gamma distribution with shape $1$ and rate $1$. What proportion of these draws are less than $1$? Provide your code.

(d) Make two histograms next to each other, one being the histogram you constructed in (b) and the other being a histogram of the draws from (c) that are less than $1$, using the same arguments for both. Overlay a line for the density of a truncated gamma random variable with shape $1$ and rate $1$ constrained to be less than $1$ on both plots.

(e) In at most one sentence, describe whether or not it seems that both methods produce draws from the same distribution.

(f) In at most one sentence, describe how the number of draws produced by the two methods compares. Is one more efficient than the other?